apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ghcr.io/cpuhyong/cicdtest:c7dcbe566294f74f5b68fc6b1a2a1f4dfa8c6a46
        ports:
        - containerPort: 80
